### PR TITLE
Ignore _middleware routes

### PR DESCRIPTION
**Pull request by johnsardine**
Next.js 12 introduced [Middlewares](https://nextjs.org/docs/middleware), this consists in `_middleware` files existing in the pages folder. Currently next-sitemap does not know it should ignore these files because they don't necessarily live at the root folder like other next.js files, so this change updates the `isNextInternalUrl` to consider paths with `_middleware` at the end of the path as internal urls.

### CODE REVIEW

**Review by iamvishnusankar — COMMENTED** [review]
@johnsardine Once again, Thanks a lot for one more awesome PR!! 

Can you please add test case which identifies middleware routes with url params. `/projects/[id]/_middleware`

It would make the regex bit more solid.!

**Comment by johnsardine** [comment]
> @johnsardine Once again, Thanks a lot for one more awesome PR!!
> 
> Can you please add test case which identifies middleware routes with url params. `/projects/[id]/_middleware`
> 
> It would make the regex bit more solid.!

I added the exact path you suggested. Before comitting I tested the following folder structure

Screenshot 2022-01-12 at 16 55 07


And interestingly the sitemap only ended up containing one `_middleware` path, coming from `/project/_middleware`. Paths with query only contained the path with the id `/project/one` and `/project/two` in my example. No `_middleware` in this case. But it's good to know the regexp still handles it correctly

**Review by iamvishnusankar — APPROVED** [review]
@johnsardine Yes, it already takes care of url params, that's why the `/projects/[id]/_middleware` is being ignore. I just suggested to add this test case to make it bit more solid :)

Thanks for adding the new test case and thanks for all your contributions so far. Approved!

**Comment by johnsardine** [comment]
> @johnsardine Yes, it already takes care of url params, that's why the `/projects/[id]/_middleware` is being filtered out. I just suggested to add this test case to make it bit more solid :)
> 
> Thanks for adding the new test case and thanks for all your contributions so far. Approved!

Got it. You’re welcome. Thanks for the prompt review and merge

**Pull request merged**
