### PR TITLE
Fix excludes not working for sitemaps

### PR DESCRIPTION
**Pull request by FINDarkside**
Fixes bug #481 introduced in #400

I didn't change the readme in this PR but it also seems like all the exclude examples there don't work. `exclude: ['/server-sitemap-index.xml'` won't exclude anything but `exclude: ['*/server-sitemap-index.xml']`will. It's because matcher will add ^ to start of every pattern. Not sure if the excludes are used in some context where it's not filtering full urls, I guess it would work in that scenario.

### CODE REVIEW

**Review by iamvishnusankar — COMMENTED** [review]
@FINDarkside Thanks for this PR, can you please consider adding some tests for this?

**Comment by FINDarkside** [comment]
That's a bit hard since there's no tests for `exportable-builder` at the moment and I don't really know what it's for, what it's supposed to do and so on. It's pretty confusing that sitemaps from `robotsTxtOptions.additionalSitemaps` go to `sitemap.xml`.

Note that without this fix I don't think it's possible to use dynamic sitemap indexes with this library. I've used [patch-package](https://www.npmjs.com/package/patch-package) to ship this change in my project. But at this point I'm not going to put in the effort to understand the module enough to write tests for it. You can do whatever you want with this PR.

**Comment by workpush** [comment]
> ...It's pretty confusing that sitemaps from `robotsTxtOptions.additionalSitemaps` go to `sitemap.xml`, which in my opinion is the real bug. But this change is more backwards compatible than reverting that logic...

I think so, too! Even the README.md is currently saying:
> List the dynamic sitemap page in robotsTxtOptions.additionalSitemaps and exclude this path from static sitemap list.
Which is not working for us.

I think, there should be a way to also add additional sitemaps just to the `IndexSitemap` and not to the `robot.txt`. What do you think?

**Comment by vladles** [comment]
It works for me! @FINDarkside Thanks!
I used patch-package - the best solution at this moment.

**Review by iamvishnusankar — APPROVED** [review]
@FINDarkside Thanks for the PR. Approved 🙏

**Comment by joan-saum** [comment]
Hey @iamvishnusankar , can this PR be merged ?

**Pull request closed without merging**
