### PR TITLE
Add support for i18n

### PR DESCRIPTION
**Pull request by johnsardine**
Adds support for i18n routing

https://nextjs.org/docs/advanced-features/i18n-routing

Fixes existing issue where defaultLocale was added to the routes when it shouldn't

### CODE REVIEW

**Comment by johnsardine** [comment]
Hi @iamvishnusankar thanks for creating this package. It's very useful however I encountered some issues when using with the i18n routing of next. https://nextjs.org/docs/advanced-features/i18n-routing

The issues I encountered were mostly related to the sitemap containing the default language urls. We could, in theory, use the transform function to replace this locale from the url but for certain static pages we'd end up with duplicate urls in the sitemap, so I took this a step further and changed the package to handle this internally by replacing the default locale when i18n is enabled and then remove any duplicates with the already included Set.

One thing I'm not sure how it should be handled is the exclusions, should we automatically ignore all languages given a path? Should users have to ignore paths including the language? Can we make it so that some sort of format can be matched? Like /*/about where * represents the locale? This will probably conflict with other exclusion patterns but I think a similar approach is probably desired.

Also, my knowledge if typescript is pretty much 0 so I did my best to honor your existing code. Also, my approach to get the i18n config is probably not ideal but it was the easiest thing for me to change given my lack of knowledge of the codebase.

Anyway, I'd love to be able to have this feature in the package so I'm open to all feedback so we can move this forward and close issues #127 and #134

Thank you

**Comment by johnsardine** [comment]
I'm not sure why the pipeline failed as I don't have access to azure, if you share the error with me I'm happy to take a look. The tests pass locally

**Comment by johnsardine** [comment]
HI @iamvishnusankar Did you have a chance to look at the PR? Thank you

**Comment by iamvishnusankar** [comment]
@johnsardine Thanks a lot for this PR. This is a really needed feature. Looks like the errors are regarding linting. Just run `yarn format` and it should fix the issue.

**Comment by johnsardine** [comment]
> @johnsardine Thanks a lot for this PR. This is a really needed feature. Looks like the errors are regarding linting. Just run `yarn format` and it should fix the issue.

Thanks, just ran it and pushed my changes. I didn't realize I had to do that. Thank you

**Comment by johnsardine** [comment]
By the way, I tested the package in next 12 and it does not work as expected. I plan to also contribute with that change soon as we want to migrate our projects to next 12 and we use your package.

**Comment by iamvishnusankar** [comment]
@johnsardine I was midway working on adding support for `i18n`. But v12 introduced a lot of changes. So reworking base logic now.

This project is using prettier as default file formatter. So that formatting is required to just keep things clean.

**Comment by johnsardine** [comment]
> @johnsardine I was midway working on adding support for `i18n`. But v12 introduced a lot of changes. So reworking base logic now.
> 
> This project is using prettier as default file formatter. So that formatting is required to just keep things clean.

It does seem to have introduced a lot of changes. If there anything I can contribute with?

**Comment by iamvishnusankar** [comment]
No, nothing at this point. Let's wait for a majority of users to migrate to V12 first. What issues needs to be solved will be more obvious by that time.

**Review by willin — APPROVED** [review]
LGTM 👍🏻

**Comment by johnsardine** [comment]
@iamvishnusankar @willin How does it work to merge the changes and release a new version? It was approved but I'm not able to merge, which makes sense given I'm not a maintainer.

Thank you

**Comment by willin** [comment]
click `Files Changed` tab, find a green button called `Review Changes` 

approve and submit. then you can merge it.

**Comment by johnsardine** [comment]
@willin thank you, but being the author, I'm not allowed to approve my own changes. Any ideas @iamvishnusankar ? Thank you

**Review by thomasrothgrabx — APPROVED** [review]

**Comment by johnsardine** [comment]
I don't have permissions to merge. I guess this will have to wait for the maintainer availability. Thanks everyone

**Comment by johnsardine** [comment]
@iamvishnusankar is there any change you'd like me to make to this PR before it's good to merge? Thank you

**Comment by tkhquang** [comment]
Without this PR merged, is there any working workaround for this? I've tried some custom `transform` but they didn't work as expected :(

**Comment by johnsardine** [comment]
@iamvishnusankar are you available to release this fix? Thank you

**Comment by iamvishnusankar** [comment]
@johnsardine I'm extremely sorry for the delay. I was away with some busy work! I've merged it!. Many thanks for this much needed PR ❤️ ✨

**Pull request merged**
