### PR TITLE
Allow passing alternate urls when transforming

### PR DESCRIPTION
**Pull request by philippeauriach**
`alternateRefs` works great when using just a different subdomain for alternate pages.

But sometimes we use the path for the language, and have translated paths, therefore the following are alternate pages : 

`https://example.com/hello`
`https://example.com/fr/bonjour`
`https://example.com/es/hola`

We need to be able to set the full alternate url when transforming the sitemap entry.

### CODE REVIEW

**Comment by gabsgasps** [comment]
any updates ?

**Comment by philippeauriach** [comment]
@iamvishnusankar so you're just not interested ? any explanation on why you closed this PR without merging it would be cool.

**Comment by iamvishnusankar** [comment]
@philippeauriach Thanks a lot for your contribution. I'm extremely sorry it was just an accident. (Happened with #188 as well).

 I was really busy with my personal projects. I just got some spare time today and was reviewing all PR. I accidentally closed your PR when bulk closing a lot of depadabot minor version bumps. Just re-opened and I'll review it now.

**Comment by philippeauriach** [comment]
No problem, it happens ! Thanks

**Comment by philippeauriach** [comment]
@iamvishnusankar I merged master, feel free to review the PR any time convenient for you!

thanks

**Pull request closed without merging**
