### PR TITLE
[Fix] Url encoding in images, dont render undefined images

### PR DESCRIPTION
**Pull request by jonluca**
The library was outputting invalid xml for URLs with query params.

This PR:

* Adds validation to the XML created
* Encodes the hrefs
* Adds safety guards to image creation
* Tests the new implementation

### CODE REVIEW

**Comment by jonluca** [comment]
Fixes https://github.com/iamvishnusankar/next-sitemap/issues/714

**Comment by kevinrobert3** [comment]
Can this be merged please?

**Comment by kevinrobert3** [comment]
@iamvishnusankar can you merge this

**Comment by iamvishnusankar** [comment]
@jonluca Thanks a lot for this PR. I'm extremely sorry for taking this long to review this. Got busy with few personal projects.

Looks like the build is failing due to incompatibility of node version. Can you please update the action file to set the node versions to `['18', '20']`. https://github.com/iamvishnusankar/next-sitemap/blob/25bad1d8f274eba4b00702dbd7f4af2132e473c6/.github/workflows/test.yml#L17

Once you push the changes, I'll merge the PR.

**Comment by jonluca** [comment]
Done

**Comment by jonluca** [comment]
Pushed another update updating yarn. We probably shouldn't use `yarn set version stable` in CI as that'll try and make an actual change if there's a new version

**Comment by iamvishnusankar** [comment]
> Pushed another update updating yarn. We probably shouldn't use `yarn set version stable` in CI as that'll try and make an actual change if there's a new version

@jonluca Yeah, Looks like the command is setting v4 now and it seems not resolving workspace modules. I tried upgrading the project to `bun` but some tests are not covered by `bun:test`

**Comment by jonluca** [comment]
We could probably move to `bun` for package installs but keep `jest` for tests

I just pushed an update to use bun to install the packages, but keep jest around for the tests. I think it all passes?

**Comment by iamvishnusankar** [comment]
@jonluca Thanks a lot for this PR! I have merged it! 🙏 

Looks like there are some issues with the release pipeline. I'll be fixing it this weekend along with much needed fix for app dir routes groups.

**Comment by sandrooco** [comment]
Hi @iamvishnusankar, do you already have a rough estimate on when this will be released?
Thank you very much for providing this package!

**Pull request merged**
